sudo: false
language: erlang
install: 'true'
otp_release:
- 19.0
- 18.0
- 17.5
- R16B03-1
- R15B03
before_script: "./bootstrap"
script: "./rebar3 ct"
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.cache/rebar3/hex/default"
deploy:
  provider: releases
  api_key:
    secure: MjloYuaQF3cd3Oab57zqwPDLPqt5MDgBIrRLpXOQwNovr2tnkKd4aJK3QJ3pTxvZievjgl+qIYI1IZyjuRV37nkjAfMw14iig959wi0k8XTJoMdylVxE5X7hk4SiWhX/ycnJx3C28PPw1OitGTF76HAJDMgEelNdoNt+hvjvDEo=
  file: rebar3
  on:
    repo: erlang/rebar3
    tags: true
